# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nikola-miljkovic/Projects/niki_asm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nikola-miljkovic/Projects/niki_asm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikola-miljkovic/Projects/niki_asm/CMakeFiles /home/nikola-miljkovic/Projects/niki_asm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikola-miljkovic/Projects/niki_asm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named apidoc_forced

# Build rule for target.
apidoc_forced: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 apidoc_forced
.PHONY : apidoc_forced

# fast build rule for target.
apidoc_forced/fast:
	$(MAKE) -f CMakeFiles/apidoc_forced.dir/build.make CMakeFiles/apidoc_forced.dir/build
.PHONY : apidoc_forced/fast

#=============================================================================
# Target rules for targets named apidoc

# Build rule for target.
apidoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 apidoc
.PHONY : apidoc

# fast build rule for target.
apidoc/fast:
	$(MAKE) -f CMakeFiles/apidoc.dir/build.make CMakeFiles/apidoc.dir/build
.PHONY : apidoc/fast

#=============================================================================
# Target rules for targets named nas

# Build rule for target.
nas: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nas
.PHONY : nas

# fast build rule for target.
nas/fast:
	$(MAKE) -f CMakeFiles/nas.dir/build.make CMakeFiles/nas.dir/build
.PHONY : nas/fast

#=============================================================================
# Target rules for targets named nas_run

# Build rule for target.
nas_run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nas_run
.PHONY : nas_run

# fast build rule for target.
nas_run/fast:
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/build
.PHONY : nas_run/fast

# target to build an object file
nas/as.o:
	$(MAKE) -f CMakeFiles/nas.dir/build.make CMakeFiles/nas.dir/nas/as.o
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/nas/as.o
.PHONY : nas/as.o

# target to preprocess a source file
nas/as.i:
	$(MAKE) -f CMakeFiles/nas.dir/build.make CMakeFiles/nas.dir/nas/as.i
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/nas/as.i
.PHONY : nas/as.i

# target to generate assembly for a file
nas/as.s:
	$(MAKE) -f CMakeFiles/nas.dir/build.make CMakeFiles/nas.dir/nas/as.s
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/nas/as.s
.PHONY : nas/as.s

# target to build an object file
nas/nas.o:
	$(MAKE) -f CMakeFiles/nas.dir/build.make CMakeFiles/nas.dir/nas/nas.o
.PHONY : nas/nas.o

# target to preprocess a source file
nas/nas.i:
	$(MAKE) -f CMakeFiles/nas.dir/build.make CMakeFiles/nas.dir/nas/nas.i
.PHONY : nas/nas.i

# target to generate assembly for a file
nas/nas.s:
	$(MAKE) -f CMakeFiles/nas.dir/build.make CMakeFiles/nas.dir/nas/nas.s
.PHONY : nas/nas.s

# target to build an object file
nas/reloc.o:
	$(MAKE) -f CMakeFiles/nas.dir/build.make CMakeFiles/nas.dir/nas/reloc.o
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/nas/reloc.o
.PHONY : nas/reloc.o

# target to preprocess a source file
nas/reloc.i:
	$(MAKE) -f CMakeFiles/nas.dir/build.make CMakeFiles/nas.dir/nas/reloc.i
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/nas/reloc.i
.PHONY : nas/reloc.i

# target to generate assembly for a file
nas/reloc.s:
	$(MAKE) -f CMakeFiles/nas.dir/build.make CMakeFiles/nas.dir/nas/reloc.s
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/nas/reloc.s
.PHONY : nas/reloc.s

# target to build an object file
nas/symbol.o:
	$(MAKE) -f CMakeFiles/nas.dir/build.make CMakeFiles/nas.dir/nas/symbol.o
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/nas/symbol.o
.PHONY : nas/symbol.o

# target to preprocess a source file
nas/symbol.i:
	$(MAKE) -f CMakeFiles/nas.dir/build.make CMakeFiles/nas.dir/nas/symbol.i
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/nas/symbol.i
.PHONY : nas/symbol.i

# target to generate assembly for a file
nas/symbol.s:
	$(MAKE) -f CMakeFiles/nas.dir/build.make CMakeFiles/nas.dir/nas/symbol.s
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/nas/symbol.s
.PHONY : nas/symbol.s

# target to build an object file
nas_run/emulator.o:
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/nas_run/emulator.o
.PHONY : nas_run/emulator.o

# target to preprocess a source file
nas_run/emulator.i:
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/nas_run/emulator.i
.PHONY : nas_run/emulator.i

# target to generate assembly for a file
nas_run/emulator.s:
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/nas_run/emulator.s
.PHONY : nas_run/emulator.s

# target to build an object file
nas_run/nas_run.o:
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/nas_run/nas_run.o
.PHONY : nas_run/nas_run.o

# target to preprocess a source file
nas_run/nas_run.i:
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/nas_run/nas_run.i
.PHONY : nas_run/nas_run.i

# target to generate assembly for a file
nas_run/nas_run.s:
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/nas_run/nas_run.s
.PHONY : nas_run/nas_run.s

# target to build an object file
nas_run/nas_util.o:
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/nas_run/nas_util.o
.PHONY : nas_run/nas_util.o

# target to preprocess a source file
nas_run/nas_util.i:
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/nas_run/nas_util.i
.PHONY : nas_run/nas_util.i

# target to generate assembly for a file
nas_run/nas_util.s:
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/nas_run/nas_util.s
.PHONY : nas_run/nas_util.s

# target to build an object file
parser/parser.o:
	$(MAKE) -f CMakeFiles/nas.dir/build.make CMakeFiles/nas.dir/parser/parser.o
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/parser/parser.o
.PHONY : parser/parser.o

# target to preprocess a source file
parser/parser.i:
	$(MAKE) -f CMakeFiles/nas.dir/build.make CMakeFiles/nas.dir/parser/parser.i
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/parser/parser.i
.PHONY : parser/parser.i

# target to generate assembly for a file
parser/parser.s:
	$(MAKE) -f CMakeFiles/nas.dir/build.make CMakeFiles/nas.dir/parser/parser.s
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/parser/parser.s
.PHONY : parser/parser.s

# target to build an object file
parser/string_util.o:
	$(MAKE) -f CMakeFiles/nas.dir/build.make CMakeFiles/nas.dir/parser/string_util.o
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/parser/string_util.o
.PHONY : parser/string_util.o

# target to preprocess a source file
parser/string_util.i:
	$(MAKE) -f CMakeFiles/nas.dir/build.make CMakeFiles/nas.dir/parser/string_util.i
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/parser/string_util.i
.PHONY : parser/string_util.i

# target to generate assembly for a file
parser/string_util.s:
	$(MAKE) -f CMakeFiles/nas.dir/build.make CMakeFiles/nas.dir/parser/string_util.s
	$(MAKE) -f CMakeFiles/nas_run.dir/build.make CMakeFiles/nas_run.dir/parser/string_util.s
.PHONY : parser/string_util.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... apidoc_forced"
	@echo "... apidoc"
	@echo "... nas"
	@echo "... nas_run"
	@echo "... nas/as.o"
	@echo "... nas/as.i"
	@echo "... nas/as.s"
	@echo "... nas/nas.o"
	@echo "... nas/nas.i"
	@echo "... nas/nas.s"
	@echo "... nas/reloc.o"
	@echo "... nas/reloc.i"
	@echo "... nas/reloc.s"
	@echo "... nas/symbol.o"
	@echo "... nas/symbol.i"
	@echo "... nas/symbol.s"
	@echo "... nas_run/emulator.o"
	@echo "... nas_run/emulator.i"
	@echo "... nas_run/emulator.s"
	@echo "... nas_run/nas_run.o"
	@echo "... nas_run/nas_run.i"
	@echo "... nas_run/nas_run.s"
	@echo "... nas_run/nas_util.o"
	@echo "... nas_run/nas_util.i"
	@echo "... nas_run/nas_util.s"
	@echo "... parser/parser.o"
	@echo "... parser/parser.i"
	@echo "... parser/parser.s"
	@echo "... parser/string_util.o"
	@echo "... parser/string_util.i"
	@echo "... parser/string_util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

